import type { AppProps } from 'next/app'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
